extends: existence
message: "Avoid using first-person like '%s'. Use Amplitude, a product name, or the other company name."
ignorecase: true
level: warning
nonword: true
tokens:
  - we
  - we'(?:ve|re)
  - ours?
  - our
  - us
  - let's
raw:
  - (?:^|\s)I\s(?!want)