title: Default
fields:
  -
    handle: content
    field:
      type: markdown
      antlers: true
      display: Content
      localizable: true
  -
    handle: author
    field:
      type: users
      display: Author
      default: current
      localizable: true
      max_items: 1
  -
    handle: template
    field:
      type: template
      display: Template
      localizable: true
