title: Chart
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: content
            field:
              type: markdown
              antlers: true
              display: Content
              localizable: true
          -
            handle: author
            field:
              type: users
              display: Author
              default: current
              localizable: true
              max_items: 1
          -
            handle: template
            field:
              type: template
              display: Template
              localizable: true
  landing_page:
    display: 'Landing page'
    sections:
      -
        display: 'Landing page'
        fields:
          -
            import: article_common
          -
            handle: icon
            field:
              max_files: 1
              container: assets
              folder: icons/features
              restrict: true
              type: assets
              display: Icon
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: parent
            field:
              type: entries
              collections:
                - charts
              max_items: 1
              listable: false
              localizable: true
  alt_sitemap:
    display: 'Alt Sitemap'
    sections:
      -
        fields:
          -
            handle: sitemap_priority
            field:
              type: float
              display: 'Sitemap Priority'
              instructions: 'From 0.0 (lowest priority) to 1.0 (highest priority)'
          -
            handle: exclude_from_sitemap
            field:
              type: toggle
              display: 'Exclude from sitemap?'
