title: Chart
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            import: help_center_common
            config:
              title:
                required: true
  landing_page:
    display: 'Landing page'
    sections:
      -
        display: 'Landing page'
        fields:
          -
            import: article_common
          -
            handle: icon
            field:
              max_files: 1
              container: assets
              folder: icons/features
              restrict: true
              type: assets
              display: Icon
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: parent
            field:
              type: entries
              collections:
                - charts
              max_items: 1
              listable: false
              localizable: true
          -
            handle: source
            field:
              type: text
              display: Source
  alt_sitemap:
    display: 'Alt Sitemap'
    sections:
      -
        fields:
          -
            handle: sitemap_priority
            field:
              type: float
              display: 'Sitemap Priority'
              instructions: 'From 0.0 (lowest priority) to 1.0 (highest priority)'
          -
            handle: exclude_from_sitemap
            field:
              type: toggle
              display: 'Exclude from sitemap?'
