---
# MegaLinter GitHub Action configuration file for our daily link check.
# This action runs a link check on our entire doc set every day at 12:00 AM so we're warned when a link breaks.
# This is a separate workflow file from main Megalinter checks because we needed to use different settings for this run.

name: Daily Link Check
on:
  schedule:
  # Run everyday at 12:00 AM
  - cron: "0 0 * * *"

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      # Git Checkout
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0


      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Adjust as needed
          extensions: bcmath, ctype, exif, json, mbstring, openssl, pdo, tokenizer, xml, gd
          tools: composer, php-cs-fixer

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install NPM Dependencies
        run: npm install
      # External Link Check
      - name: Internal Link Check
        run: ./linkchecker external
