name: Build and Deploy Statamic Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Adjust as needed
        extensions: bcmath, ctype, exif, json, mbstring, openssl, pdo, tokenizer, xml, gd
        tools: composer, php-cs-fixer

    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Specify the Node.js version you need

    - name: Install NPM Dependencies
      run: npm install

    - name: Build Assets
      run: npm run build # Replace "build" with your front-end build script if it's named differently

    - name: Build Static Site
      run: php please ssg:generate

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: storage/app/static
  
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
        pages: write      # to deploy to Pages
        id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
